#include "htmlwirter(repaly_Week09_03).h"
#include<fstream>
using namespace std;

HTMLWriter::HTMLWriter(const string& fileName, const string& content)
	:DocWriter(fileName, content) {//:DocWriter(fileName, content) 초기화 리스트 / 부모 매서드로 초기화함
	_fontName = "굴림";
	_fontSize = 3;
	_fontColor = "red";
}

HTMLWriter::HTMLWriter() {
	_fileName = "NoName.html";

	_fontName = "굴림";
	_fontSize = 3;
	_fontColor = "red";
}
HTMLWriter::~HTMLWriter() {

}

void HTMLWriter::Write() {
	ofstream of(_fileName.c_str() ); //메서드 오버라이딩

	of << "<HTML><HEAD><TITLE>This document was generated by HTMLWriter < /TITLE > < /HEAD> < /HTML>";
	of << "<H1>Content</H1>";

	of << "<Font name='" << _fontName << "'size='" << _fontSize << "'color='" << _fontColor<<"'>";

	of << _content;
	of << "</FONT>";
	of << "</BODY></HTML>";
}
void HTMLWriter::SetFont(const string& fontName, int fontSize, const string& fontColor) {
	_fontName = fontName;
	_fontSize = fontSize;
	_fontColor = fontColor;
}